name: ci

on: [push, pull_request, workflow_dispatch]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install flit
        run: pip install flit

      - name: Install package
        run: flit install

      - name: Test with pytest
        run: pytest tests/ --cov=ucell --cov-report=xml

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml # coverage report

      - name: Build documentation
        run: make html --directory docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs/_build/html


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
