name: ci

on: [push, pull_request]

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Install flit
        run: pip install flit

      - name: Install package
        run: flit install

      - name: Test with pytest
        run: pytest tests/ 

      - name: Use Codecov to track coverage
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml # coverage report

      - name: Build documentation
        run: make html --directory docs/
